library(dplyr)
library(plyr)
library(ggplot2)

severity_to_aki_times <- aki_only_index %>% select(severe,severe_to_aki)
severity_to_aki_plot <- ggplot(severity_to_aki_times,aes(x=severe_to_aki)) + geom_density() + geom_vline(aes(xintercept=mean(severe_to_aki)),color="blue",linetype="dashed",size=1)
mu <- severity_to_aki_times %>% group_by(severe) %>% summarise(mean_time = mean(severe_to_aki))
severity_to_aki_categ_plot <- ggplot(severity_to_aki_times,aes(x=severe_to_aki,color=severe)) + geom_density() + geom_vline(data=mu,aes(xintercept=mean_time,color = severe),linetype="dashed")
print(severity_to_aki_plot)
print(severity_to_aki_categ_plot)
